-- PROJECT
DROP TABLE IF EXISTS PROJECTS RESTRICT;

-- 협업자
DROP TABLE IF EXISTS COLLABO RESTRICT;

-- MEMBERS
DROP TABLE IF EXISTS USERS RESTRICT;

-- PROJECT
CREATE TABLE PROJECTS (
	PID   VARCHAR(40)  NOT NULL COMMENT '프로젝트일련번호', -- 프로젝트일련번호
	PNAME VARCHAR(40)  NOT NULL COMMENT '프로젝트명', -- 프로젝트명
	PDATE DATE         NOT NULL COMMENT '생성일', -- 생성일
	PMEMO VARCHAR(255) NULL     COMMENT '메모' -- 메모
)
COMMENT 'PROJECT';

-- PROJECT
ALTER TABLE PROJECTS
	ADD CONSTRAINT PK_PROJECTS -- PROJECT 기본키
		PRIMARY KEY (
			PID -- 프로젝트일련번호
		);

-- 협업자
CREATE TABLE COLLABO (
	UID  VARCHAR(40) NOT NULL COMMENT '아이디', -- 아이디
	PID  VARCHAR(40) NOT NULL COMMENT '프로젝트일련번호', -- 프로젝트일련번호
	AUTH VARCHAR(10) NOT NULL COMMENT '권한' -- 권한
)
COMMENT '협업자';

-- 협업자
ALTER TABLE COLLABO
	ADD CONSTRAINT PK_COLLABO -- 협업자 기본키
		PRIMARY KEY (
			UID, -- 아이디
			PID  -- 프로젝트일련번호
		);

-- MEMBERS
CREATE TABLE USERS (
	UID   VARCHAR(40)  NOT NULL COMMENT '아이디', -- 아이디
	PWD   VARCHAR(40)  NOT NULL COMMENT '비밀번호', -- 비밀번호
	EMAIL VARCHAR(40)  NOT NULL COMMENT '이메일', -- 이메일
	GURL  VARCHAR(255) NULL     COMMENT '기트주소' -- 기트주소
)
COMMENT 'MEMBERS';

-- MEMBERS
ALTER TABLE USERS
	ADD CONSTRAINT PK_USERS -- MEMBERS 기본키
		PRIMARY KEY (
			UID -- 아이디
		);

-- MEMBERS 유니크 인덱스
CREATE UNIQUE INDEX UIX_USERS
	ON USERS ( -- MEMBERS
		EMAIL ASC -- 이메일
	);

-- 협업자
ALTER TABLE COLLABO
	ADD CONSTRAINT FK_USERS_TO_COLLABO -- MEMBERS -> 협업자
		FOREIGN KEY (
			UID -- 아이디
		)
		REFERENCES USERS ( -- MEMBERS
			UID -- 아이디
		);

-- 협업자
ALTER TABLE COLLABO
	ADD CONSTRAINT FK_PROJECTS_TO_COLLABO -- PROJECT -> 협업자
		FOREIGN KEY (
			PID -- 프로젝트일련번호
		)
		REFERENCES PROJECTS ( -- PROJECT
			PID -- 프로젝트일련번호
		);